### PR TITLE
PT-1247 Allow by Configuration the parallel logins of same account

### PR DESCRIPTION
**Pull request by CedricPerotto**

### CODE REVIEW

**Review by franck-fourel — APPROVED** [review]
LGTM
one minor comment: can you update the vscode template so that it contains the new variable, even if we set it to false.

**Comment by CedricPerotto** [comment]
> LGTM
> one minor comment: can you update the vscode template so that it contains the new variable, even if we set it to false.

Done

**Review by franck-fourel — COMMENTED** [review]
one more thing: let's release it. 
Can you please update the release number to 0.6.0 ?

**Review by franck-fourel — APPROVED** [review]
LGTM

**Pull request merged**
